; Generated by tools/import_kof95_kim.py from Kak2X/kof95
; Source commit: d1a2372dbfc474ddcbb94a69ffdb4546a8d5ed08
MoveC_Kim_ThrowG:
	mMvC_ValLoaded .ret
	; Depending on the visible frame...
	mMvC_StartChkFrame
		mMvC_ChkFrame $00, .obj0
		mMvC_ChkFrame $01, .obj1
		mMvC_ChkFrame $02, .chkEnd
	jp   .anim ; We never get here
; --------------- frame #0 ---------------
.obj0:
	mMvC_ValFrameEnd .anim
		mMvC_SetDamageNext $06, HITTYPE_GRAB_START, PF3_HEAVYHIT
		jp   .anim
; --------------- frame #1 ---------------
; When visually switching to #2, hit the opponent.
.obj1:
	mMvC_ValFrameEnd .anim
		mMvC_SetDamageNext $06, HITTYPE_LAUNCH_MID_UB_NOSTUN, PF3_HEAVYHIT
		jp   .anim
; --------------- frame #2 ---------------
.chkEnd:
	; Wait for the animation to advance before ending the move
	mMvC_ValFrameEnd .anim
		; And when it does, also reset the throw sequence
		mMvC_EndThrow
		jr   .ret
; --------------- common ---------------
.anim:
	jp   OBJLstS_DoAnimTiming_Loop_by_DE
.ret:
	ret

; =============== MoveC_Kim_KickHN ===============
; Move code for Kim's Near Heavy Kick (MOVE_SHARED_KICK_HN).
MoveC_Kim_KickHN:
	call Play_Pl_MoveByColiBoxOverlapX
	mMvC_ValLoaded .ret
	; Depending on the visible frame...
	mMvC_StartChkFrame
		mMvC_ChkFrame $00, .obj0
		mMvC_ChkFrame $02, .chkEnd
; --------------- frame #1 ---------------
	jp   .anim
; --------------- frame #0 ---------------
; Set damage at the end.
.obj0:
	mMvC_ValFrameEnd .anim
		mMvC_SetDamageNext $06, HITTYPE_HIT_MID1, PF3_HEAVYHIT
		jp   .anim
; --------------- frame #2 ---------------
.chkEnd:
	mMvC_ValFrameEnd .anim
		call Play_Pl_EndMove
		jr   .ret
; --------------- common ---------------
.anim:
	jp   OBJLstS_DoAnimTiming_Loop_by_DE
.ret:
	ret
	
; =============== MoveC_Kim_KickHM ===============
; Move code for Kim's Far Heavy Kick (MOVE_SHARED_KICK_HM).	
MoveC_Kim_KickHM:
	call Play_Pl_MoveByColiBoxOverlapX
	mMvC_ValLoaded .ret
	; Depending on the visible frame...
	mMvC_StartChkFrame
		mMvC_ChkFrame $02, .obj2
		mMvC_ChkFrame $03, .obj3
		mMvC_ChkFrame $04, .obj4
		mMvC_ChkFrame $05, .obj5
; --------------- frames #0-1 ---------------
	jp   .anim
; --------------- frame #2 ---------------
.obj2:
	mMvC_ValFrameStartFast .obj2_cont
		mMvC_SetMoveH +$0400
.obj2_cont:
	mMvC_ValFrameEnd .anim
		mMvC_PlaySound SFX_HEAVY
		jp   .anim
; --------------- frame #2 ---------------
.obj3:
	mMvC_ValFrameStartFast .obj3_cont
		mMvC_SetMoveH +$0600
.obj3_cont:
	mMvC_ValFrameEnd .anim
		mMvC_SetDamageNext $08, HITTYPE_HIT_MID0, PF3_HEAVYHIT
		jp   .anim
; --------------- frame #2 ---------------
.obj4:
	mMvC_ValFrameStartFast .obj4_cont
		mMvC_SetMoveH +$0600
.obj4_cont:
	jp   .anim
; --------------- frame #2 ---------------
.obj5:
	mMvC_ValFrameStartFast .chkEnd
		mMvC_SetMoveH +$0400
.chkEnd:
	mMvC_ValFrameEnd .anim
		call Play_Pl_EndMove
		jr   .ret
; --------------- common ---------------
.anim:
	jp   OBJLstS_DoAnimTiming_Loop_by_DE
.ret:
	ret  
	
; =============== MoveInputReader_Kim ===============
; Special move input checker for KIM.
; IN
; - BC: Ptr to wPlInfo
; - DE: Ptr to respective wOBJInfo
; OUT
; - C flag: If set, a move was started
MoveC_Kim_HanGetsuZan:
	call Play_Pl_MoveByColiBoxOverlapX
	mMvC_ValLoaded .ret
	; Depending on the visible frame...
	mMvC_StartChkFrame
		mMvC_ChkFrame $00, .obj0
		mMvC_ChkFrame $01, .obj1
		mMvC_ChkFrame $02, .chkGravity
		mMvC_ChkFrame $05, .chkEnd
; --------------- frame #3-4 ---------------
	jp   .anim
; --------------- frame #0 ---------------
.obj0:
	mMvC_ValFrameStartFast .obj0_cont
		mMvC_SetMoveH +$0600
.obj0_cont:
	mMvC_ValFrameEnd .anim
		; From the next frame, knockdown on contact
		mMvC_SetAnimSpeed ANIMSPEED_NONE
		mMvC_SetDamageNext $08, HITTYPE_LAUNCH_HIGH_UB, PF3_HEAVYHIT
		jp   .anim
; --------------- frame #1 ---------------
.obj1:
	mMvC_ValFrameStartFast .obj1_cont
		mMvC_PlaySound SCT_MOVEJUMP_B
		;--
		ld   hl, iPlInfo_Flags0
		add  hl, bc
		set  PF0B_AIR, [hl]
		;--
		; Set jump speed
		mMvC_SetDamageNext $08, HITTYPE_LAUNCH_HIGH_UB, PF3_HEAVYHIT
		mMvC_ChkMove MOVE_KIM_HAN_GETSU_ZAN_H, .obj1_setJumpH
	.obj1_setJumpL: ; Light
		mMvC_SetSpeedH +$0400
		mMvC_SetSpeedV -$0300
		jp   .obj1_cont
	.obj1_setJumpH: ; Heavy
		mMvC_ChkMaxPow .obj1_setJumpE
		mMvC_SetSpeedH +$0500
		mMvC_SetSpeedV -$0380
		jp   .obj1_cont
	.obj1_setJumpE: ; Max Power Heavy
		mMvC_SetSpeedH +$0600
		mMvC_SetSpeedV -$0400
.obj1_cont:
	; Immediately go to the next frame
	mMvC_NextFrameOnGtYSpeed -$08, ANIMSPEED_NONE
	jp   .chkGravity
; --------------- common gravity check / frame #1 ---------------
.chkGravity:
	; Touching the ground switches to #2 and deals another hit
	mMvC_ChkGravityHV $0060, .anim
		;--
		; Allow special cancel
		ld   hl, iPlInfo_Flags0
		add  hl, bc
		res  PF0B_AIR, [hl]
		inc  hl
		res  PF1B_NOSPECSTART, [hl]
		;--
		mMvC_SetDamageNext $08, HITTYPE_LAUNCH_HIGH_UB, PF3_HEAVYHIT
		mMvC_SetLandFrame $03, $03
		jp   .ret
; --------------- frame #3 ---------------
.chkEnd:
	mMvC_ValFrameEnd .anim
		call Play_Pl_EndMove
		jr   .ret
; --------------- common ---------------
.anim:
	call OBJLstS_DoAnimTiming_Loop_by_DE
.ret:
	ret
	
; =============== MoveC_Kim_HienZan ===============
; Move code for Kim's Hien Zan (MOVE_KIM_HIEN_ZAN_L, MOVE_KIM_HIEN_ZAN_H)
MoveC_Kim_HienZan:
	call Play_Pl_MoveByColiBoxOverlapX
	mMvC_ValLoaded .ret
	; Depending on the visible frame...
	mMvC_StartChkFrame
		mMvC_ChkFrame $00, .anim
		mMvC_ChkFrame $01, .obj1
		mMvC_ChkFrame $02, .obj2
		mMvC_ChkFrame $03, .obj3
		mMvC_ChkFrame $04, .chkEnd
; --------------- frame #1 ---------------
.obj1:
	mMvC_ValFrameEnd .anim
		; For the gravity check
		mMvC_SetAnimSpeed ANIMSPEED_NONE
		mMvC_PlaySound SFX_MOVEJUMP_A
		; Deal hit on #2
		mMvC_SetDamageNext $08, HITTYPE_LAUNCH_HIGH_UB, PF3_HEAVYHIT
		jp   .anim
; --------------- frame #2 ---------------
.obj2:
	mMvC_ValFrameStartFast .obj2_cont
		mMvC_SetMoveH +$0800
		;--
		; Remove invuln
		ld   hl, iPlInfo_Flags0
		add  hl, bc
		set  PF0B_AIR, [hl]
		inc  hl
		res  PF1B_INVULN, [hl]
		;--
		; Set high jump speed
		mMvC_ChkMove MOVE_KIM_HIEN_ZAN_H, .obj2_setJumpH
		mMvC_SetSpeedH +$0080
		mMvC_SetSpeedV -$0600
		jp   .obj2_doGravity
	.obj2_setJumpH:
		mMvC_ChkMaxPow .obj2_setJumpE
		mMvC_SetSpeedH +$0100
		mMvC_SetSpeedV -$0700
		jp   .obj2_doGravity
	.obj2_setJumpE:
		mMvC_SetSpeedH +$0200
		mMvC_SetSpeedV -$0800
	.obj2_doGravity:
		jp   .doGravity
.obj2_cont:
	; Wait for past the peak of the jump before continuing
	mMvC_NextFrameOnGtYSpeed $01, ANIMSPEED_NONE
	jp   .doGravity
; --------------- frame #3 ---------------
.obj3:
	; Force the horizontal speed of 0.25px/frame until landing on the ground
	mMvC_SetSpeedH +$0040
; --------------- common gravity check / frames #2-3 ---------------
.doGravity:
	; When landing on the ground...
	mMvC_ChkGravityHV $0060, .anim
		;--
		; Allow special cancel
		ld   hl, iPlInfo_Flags0
		add  hl, bc
		res  PF0B_AIR, [hl]
		inc  hl
		res  PF1B_NOSPECSTART, [hl]
		;--
		; Switch to #4
		mMvC_SetLandFrame $04, $03
		jp   .ret
; --------------- frame #4 ---------------
.chkEnd:
	mMvC_ValFrameEnd .anim
		call Play_Pl_EndMove
		jr   .ret
; --------------- common ---------------
.anim:
	call OBJLstS_DoAnimTiming_Loop_by_DE
.ret:
	ret
	
; =============== MoveC_Kim_HishouKyaku ===============
; Move code for Kim's Hishou Kyaku (MOVE_KIM_HISHOU_KYAKU_L, MOVE_KIM_HISHOU_KYAKU_H)
; Dive kick.
MoveC_Kim_HishouKyaku:
	call Play_Pl_MoveByColiBoxOverlapX
	mMvC_ValLoaded .ret
	; Depending on the visible frame...
	mMvC_StartChkFrame
		mMvC_ChkFrame $00, .obj0
		mMvC_ChkFrame $01, .obj1
		mMvC_ChkFrame $02, .obj2
		mMvC_ChkFrame $03, .chkEnd
	jp   .anim ; We never get here
; --------------- frame #0 ---------------
.obj0:
	mMvC_ValFrameStartFast .obj0_chkGuard
		mMvC_PlaySound SCT_MOVEJUMP_A
		
		; Set the dive speed
		mMvC_ChkMove MOVE_KIM_HISHOU_KYAKU_H, .obj0_setJumpH
	.obj0_setJumpL: ; Light
		mMvC_SetSpeedH +$0100
		mMvC_SetSpeedV +$0100
		jp   .obj0_doGravity
	.obj0_setJumpH: ; Heavy
		mMvC_ChkMaxPow .obj0_setJumpE
		mMvC_SetSpeedH +$0300
		mMvC_SetSpeedV +$0200
		jp   .obj0_doGravity
	.obj0_setJumpE: ; Max Power Heavy
		mMvC_SetSpeedH +$0400
		mMvC_SetSpeedV +$0300
	.obj0_doGravity:
		jp   .doGravity
.obj0_chkGuard:
	;
	; Continue the dive until hitting the opponent.
	;
	ld   hl, iPlInfo_ColiFlags
	add  hl, bc
	bit  PCFB_HITOTHER, [hl]			; Did we reach?
	jp   z, .obj0_chkGuard_doGravity	; If not, skip
	ld   hl, iPlInfo_Flags1Other
	add  hl, bc
	bit  PF1B_INVULN, [hl]				; Is the opponent invulnerable?
	jp   nz, .obj0_chkGuard_doGravity	; If so, skip
	bit  PF1B_HITRECV, [hl]				; Did the opponent get hit?
	jp   z, .obj0_chkGuard_doGravity	; If not, skip	
	
	; Otherwise, deal damage to the opponent, and start the loop.
	.obj0_chkGuard_noGuard:
		mMvC_SetDamageNext $01, HITTYPE_HIT_MID1, PF3_CONTHIT
		mMvC_SetFrame $01, $00
		jp   .ret
.obj0_chkGuard_doGravity:
	jp   .doGravity
; --------------- frame #1 ---------------
; Damage loop #1
.obj1:
	mMvC_ValFrameEnd .doGravity
		mMvC_SetDamageNext $08, HITTYPE_HIT_MID0, PF3_CONTHIT
		jp   .doGravity
; --------------- frame #2 ---------------
; Damage loop #2
.obj2:
	mMvC_ValFrameEnd .doGravity
		; If we didn't touch the ground yet by the end of #2, loop back to #1
		mMvC_SetDamageNext $01, HITTYPE_HIT_MID1, PF3_CONTHIT
		mMvC_SetFrameOnEnd $01
		jp   .doGravity
; --------------- common gravity check / frames #0-2 ---------------
.doGravity:
	; When touching the ground, continue to #3
	mMvC_ChkGravityHV $0018, .anim
		;--
		; Allow special cancel
		ld   hl, iPlInfo_Flags0
		add  hl, bc
		res  PF0B_AIR, [hl]
		inc  hl
		res  PF1B_NOSPECSTART, [hl]
		;--
		mMvC_SetLandFrame $03, $05
		jp   .ret
; --------------- frame #3 ---------------
; Recovery
.chkEnd:
	mMvC_ValFrameEnd .anim
		call Play_Pl_EndMove
		jr   .ret
; --------------- common ---------------
.anim:
	call OBJLstS_DoAnimTiming_Loop_by_DE
.ret:
	ret
	
; =============== MoveC_Kim_RyuuseiRanku ===============
; Move code for Kim's Ryuusei Ranku (MOVE_KIM_RYUUSEI_RANKU_L, MOVE_KIM_RYUUSEI_RANKU_H)
; Dash, then jump kick that hits on the way up and the way down.	
MoveC_Kim_RyuuseiRanku:
	call Play_Pl_MoveByColiBoxOverlapX
	mMvC_ValLoaded .ret
	; Depending on the visible frame...
	mMvC_StartChkFrame
		mMvC_ChkFrame $00, .obj0
		mMvC_ChkFrame $01, .obj1
		mMvC_ChkFrame $02, .obj2
		mMvC_ChkFrame $03, .doGravity
		mMvC_ChkFrame $04, .chkEnd
; --------------- frame #0 ---------------
; Forwards dash
.obj0:
	mMvC_ValFrameStartFast .obj0_chkGuard
		mMvC_PlaySound SCT_MOVEJUMP_A
		
		; Set forwards dash speed
		mMvC_ChkMove MOVE_KIM_RYUUSEI_RANKU_H, .obj0_setDashH
		mMvC_SetSpeedH +$0500
		jp   .obj0_anim
	.obj0_setDashH:
		mMvC_ChkMaxPow .obj0_setDashE
		mMvC_SetSpeedH +$0600
		jp   .obj0_anim
	.obj0_setDashE:
		mMvC_SetSpeedH +$0700
	.obj0_anim:
		jp   .anim
.obj0_chkGuard:

	;
	; Continue the forwards dash until hitting the opponent, slowing down at 0.25px/frame.
	;
	ld   hl, iPlInfo_ColiFlags
	add  hl, bc
	bit  PCFB_HITOTHER, [hl]		; Did we reach?
	jp   z, .obj0_chkGuard_moveH	; If not, skip
	ld   hl, iPlInfo_Flags1Other
	add  hl, bc
	bit  PF1B_INVULN, [hl]			; Is the opponent invulnerable?
	jp   nz, .obj0_chkGuard_moveH	; If so, skip
	bit  PF1B_HITRECV, [hl]			; Did the opponent get hit?
	jp   z, .obj0_chkGuard_moveH	; If not, skip	
	
	jp   .obj0_chkGuard_noGuard
	
.obj0_chkGuard_moveH:
	; Do the movement
	mMvC_ChkFrictionH $0040, .anim
	; If we got here, by the time we stopped we still didn't hit the opponent.
	; Nothing special happens in this case, it just does the jump as normal.
	
	.obj0_chkGuard_noGuard:
		; We made contact.
		; Immediately switch to the next frame by resetting the counter and setting ANIMSPEED_INSTANT.
		ld   hl, iOBJInfo_FrameLeft
		add  hl, de
		ld   [hl], $00
		mMvC_SetAnimSpeed ANIMSPEED_INSTANT
		jp   .anim
; --------------- frame #1 ---------------
; Prepare for jumpkick.
.obj1:
	mMvC_ValFrameEnd .anim
		mMvC_SetAnimSpeed ANIMSPEED_NONE
		mMvC_PlaySound SFX_MOVEJUMP_A
		; This jumpkick drops the opponent directly down, only hitting once
		mMvC_SetDamageNext $08, HITTYPE_LAUNCH_FAST_DB, PF3_HEAVYHIT
		jp   .anim
; --------------- frame #2 ---------------
; Jumpkick up.
.obj2:
	mMvC_ValFrameStartFast .obj2_cont
		mMvC_SetMoveH +$0800
		;--
		; Remove invuln
		ld   hl, iPlInfo_Flags0
		add  hl, bc
		set  PF0B_AIR, [hl]
		inc  hl
		res  PF1B_INVULN, [hl]
		;--
		; Set jump settings
		mMvC_ChkMove MOVE_KIM_RYUUSEI_RANKU_H, .obj2_setJumpH
	.obj2_setJumpL: ; Light
		mMvC_SetSpeedH +$0180
		mMvC_SetSpeedV -$0500
		jp   .obj2_doGravity
	.obj2_setJumpH: ; Heavy
		mMvC_ChkMaxPow .obj2_setJumpE
		mMvC_SetSpeedH +$0200
		mMvC_SetSpeedV -$0500
		jp   .obj2_doGravity
	.obj2_setJumpE: ; Max Power Heavy
		mMvC_SetSpeedH +$0280
		mMvC_SetSpeedV -$0500
	.obj2_doGravity:
		jp   .doGravity
.obj2_cont:
	; Immediately go to the next frame (YSpeed always > -$06)
	mMvC_NextFrameOnGtYSpeed -$06, ANIMSPEED_NONE
	jp   .doGravity
; --------------- common gravity check / frames #2-3 ---------------
; Jumpkick down on #3
.doGravity:
	mMvC_ChkGravityHV $0060, .anim
		;--
		; Allow special cancel
		ld   hl, iPlInfo_Flags0
		add  hl, bc
		res  PF0B_AIR, [hl]
		inc  hl
		res  PF1B_NOSPECSTART, [hl]
		;--
		; Switch to #4
		mMvC_SetLandFrame $04, $05
		jp   .ret
; --------------- frame #4 ---------------
; Recovery.
.chkEnd:
	mMvC_ValFrameEnd .anim
		call Play_Pl_EndMove
		jr   .ret
; --------------- common ---------------
.anim:
	call OBJLstS_DoAnimTiming_Loop_by_DE
.ret:
	ret
	
; =============== MoveC_Kim_HouOuKyaku ===============
; Move code for Kim's Hou Ou Kyaku (MOVE_KIM_HOU_OU_KYAKU_S)
; Loads of kicks that transition to Hien Zan.
MoveC_Kim_HouOuKyaku:
	call Play_Pl_MoveByColiBoxOverlapX
	mMvC_ValLoaded .ret
	; Depending on the visible frame...
	mMvC_StartChkFrame
		mMvC_ChkFrame $00, .obj0
		mMvC_ChkFrame $01, .obj1
		mMvC_ChkFrame $02, .setDamageStart
		mMvC_ChkFrame $04, .setDamage0
		mMvC_ChkFrame $06, .setDamage0
		mMvC_ChkFrame $08, .setDamage0
		mMvC_ChkFrame $0A, .setDamage0
		mMvC_ChkFrame $0C, .setDamage0
		mMvC_ChkFrame $0E, .setDamage0
		mMvC_ChkFrame $0F, .toHienZan
		mMvC_ChkFrame $10, .chkEnd
	jp   .setDamage1
; --------------- frame #0 ---------------
; Startup.
.obj0:
	mMvC_ValFrameEnd .anim
		mMvC_SetAnimSpeed ANIMSPEED_NONE
		jp   .anim
; --------------- frame #1 ---------------
; Fast hop forwards.
.obj1:
	; Set the jump speed the first time we get here
	mMvC_ValFrameStartFast .obj1_chkGuard
		mMvC_PlaySound SCT_MOVEJUMP_A
		;--
		ld   hl, iPlInfo_Flags0
		add  hl, bc
		set  PF0B_AIR, [hl]
		;--
		mMvC_SetSpeedH +$07FF
		mMvC_SetSpeedV -$0200
		jp   .chkGravity
.obj1_chkGuard:
	;
	; Continue the jump until hitting the opponent.
	;
	ld   hl, iPlInfo_ColiFlags
	add  hl, bc
	bit  PCFB_HITOTHER, [hl]			; Did we reach?
	jp   z, .obj1_chkGuard_doGravity	; If not, skip
	ld   hl, iPlInfo_Flags1Other
	add  hl, bc
	bit  PF1B_INVULN, [hl]				; Is the opponent invulnerable?
	jp   nz, .obj1_chkGuard_doGravity	; If so, skip
	bit  PF1B_HITRECV, [hl]				; Did the opponent get hit?
	jp   z, .obj1_chkGuard_doGravity	; If not, skip	
	
	;
	; Significantly slow down if the opponent is blocking
	;
	bit  PF1B_GUARD, [hl]				; Is the opponent blocking?
	jp   nz, .obj1_chkGuard_slowdown	; If so, jump
	
	.obj1_chkGuard_noGuard:
		; Otherwise, continue to #2
		mMvC_SetDamageNext $01, HITTYPE_HIT_MULTI1, PF3_CONTHIT
		mMvC_SetFrame $02, $01
		mMvC_SetSpeedH $0000
		; Align to floor
		ld   hl, iOBJInfo_Y
		add  hl, de
		ld   [hl], PL_FLOOR_POS
		jp   .ret
		
.obj1_chkGuard_slowdown:
	mMvC_SetSpeedH +$0100
	
.obj1_chkGuard_doGravity:
	jp   .chkGravity
	
; --------------- odd frames #3,5,7,9,B ---------------
.setDamage1:
	mMvC_ValFrameStartFast .anim
		mMvC_SetDamageNext $01, HITTYPE_HIT_MULTI1, PF3_CONTHIT
		jp   .chkOtherEscape
; --------------- initial damage frame / frame #2 ---------------
.setDamageStart:
	mMvC_ValFrameStartFast .anim
		mMvC_SetDamageNext $01, HITTYPE_HIT_MULTI0, PF3_CONTHIT
		jp   .anim
; --------------- even frames #4,6,8,A,E ---------------
.setDamage0:
	mMvC_ValFrameStartFast .anim
		mMvC_SetDamageNext $01, HITTYPE_HIT_MULTI0, PF3_CONTHIT
; --------------- common escape check ---------------
.chkOtherEscape:
	;
	; [POI] If the opponent somehow isn't in one of the hit effects 
	;       this move sets, hop back instead of continuing.
	;       This can happen if the opponent gets hit by a previously thrown
	;       fireball in the middle of the move.
	;
	ld   hl, iPlInfo_HitTypeIdOther
	add  hl, bc
	ld   a, [hl]
	cp   HITTYPE_HIT_MULTI0	; A == HITTYPE_HIT_MULTI0?
	jp   z, .anim			; If so, skip
	cp   HITTYPE_HIT_MULTI1	; A == HITTYPE_HIT_MULTI1?
	jp   z, .anim			; If so, skip
		; Otherwise, transition to backjump
		ld   a, MOVE_SHARED_HOP_B
		call Pl_SetMove_StopSpeed
		jp   .ret
; --------------- final damage frame / frame #F ---------------
.toHienZan:
	; Success, transition to the new move when the frame ends.
	mMvC_ValFrameEnd .anim
		mMvC_SetDamageNext $10, HITTYPE_LAUNCH_HIGH_UB, PF3_CONTHIT
		ld   a, MOVE_KIM_HIEN_ZAN_H
		call MoveInputS_SetSpecMove_StopSpeed
		jp   .ret
; --------------- common gravity check / frame #1 ---------------
.chkGravity:
	; Touching the ground at any point during the initial forward jump switches to #10.
	mMvC_ChkGravityHV $0030, .anim
		;--
		; Allow special cancel
		ld   hl, iPlInfo_Flags0
		add  hl, bc
		res  PF0B_AIR, [hl]
		inc  hl
		res  PF1B_NOSPECSTART, [hl]
		;--
		mMvC_SetLandFrame $10, $07
		jp   .ret
; --------------- frame #10 ---------------
; Move whiffed, recovery.
.chkEnd:
	mMvC_ValFrameEnd .anim
		call Play_Pl_EndMove
		jp   .ret
; --------------- common ---------------
.anim:
	call OBJLstS_DoAnimTiming_Loop_by_DE
.ret:
	ret
