#!/usr/bin/env python3
"""Import Kim's untouched KOF95 frame data and adapt OBJ headers to KOF96."""

from __future__ import annotations

import re
import shutil
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
VENDOR = ROOT.parent / "kof95"
EXPECTED_VENDOR_COMMIT = "d1a2372dbfc474ddcbb94a69ffdb4546a8d5ed08"


def main() -> None:
    commit = subprocess.check_output(
        ["git", "rev-parse", "HEAD"], cwd=VENDOR, text=True
    ).strip()
    if commit != EXPECTED_VENDOR_COMMIT:
        raise SystemExit(f"unexpected kof95 commit: {commit}")

    source_gfx = VENDOR / "data/gfx/char"
    output_gfx = ROOT / "data/gfx/char/kof95_kim"
    output_gfx.mkdir(parents=True, exist_ok=True)
    gfx_files = sorted(source_gfx.glob("kim_*.bin"))
    if not gfx_files:
        raise SystemExit("KOF95 Kim frame data was not found")
    for source in gfx_files:
        shutil.copyfile(source, output_gfx / source.name)

    # Preserve the original KOF96 sheet and append KOF95 Kim's native icon.
    icons96 = (ROOT / "data/gfx/char_icons.bin").read_bytes()
    icons95 = (VENDOR / "data/gfx/char_icons.bin").read_bytes()
    kim_icon_95 = icons95[10 * 0x40 : 11 * 0x40]
    # KOF95 stores a 2x2 icon row-major (TL, TR, BL, BR), while KOF96's
    # drawing helpers expect column-major tiles (TL, BL, TR, BR).
    kim_icon = b"".join(
        kim_icon_95[tile * 0x10 : (tile + 1) * 0x10]
        for tile in (0, 2, 1, 3)
    )
    (ROOT / "data/gfx/char_icons_mix.bin").write_bytes(icons96 + kim_icon)

    generated = ROOT / "src/mixkof"
    generated.mkdir(parents=True, exist_ok=True)
    declarations = [
        "; Generated by tools/import_kof95_kim.py from Kak2X/kof95",
        f"; Source commit: {EXPECTED_VENDOR_COMMIT}",
    ]
    bank15 = (VENDOR / "src/bank15.asm").read_text()
    for label, filename in re.findall(
        r'^(GFX_Char_Kim_[A-Za-z0-9_]+): INCBIN "data/gfx/char/(kim_[^"]+\.bin)"$',
        bank15,
        re.MULTILINE,
    ):
        declarations.append(
            f'{label}: INCBIN "data/gfx/char/kof95_kim/{filename}"'
        )
    (generated / "kim95_gfx.asm").write_text("\n".join(declarations) + "\n")

    # KOF96 added an X offset byte immediately before the Y offset.
    obj = (VENDOR / "data/objlst/char/kim.asm").read_text()
    obj = re.sub(
        r"(?m)^(\s*)db (.+?) ; iOBJLstHdrA_YOffset$",
        r"\1db $00 ; iOBJLstHdrA_XOffset\n\1db \2 ; iOBJLstHdrA_YOffset",
        obj,
    )
    header = (
        "; Generated by tools/import_kof95_kim.py from Kak2X/kof95\n"
        f"; Source commit: {EXPECTED_VENDOR_COMMIT}\n"
    )
    (generated / "kim95_objlst.asm").write_text(header + obj)

    bank02 = (VENDOR / "src/bank02.asm").read_text()
    normals_start = bank02.index("MoveC_Kim_ThrowG:")
    input_start = bank02.index("MoveInputReader_Kim:", normals_start)
    specials_start = bank02.index("MoveC_Kim_HanGetsuZan:", input_start)
    code_end = bank02.index("; =============== END OF BANK", specials_start)
    code = bank02[normals_start:input_start] + bank02[specials_start:code_end]
    code = code.replace("HITTYPE_GRAB_UB_NOSYNC", "HITTYPE_GRAB_START")
    code = code.replace("SFX_SPECIAL", "SFX_MOVEJUMP_A")
    (generated / "kim95_code.asm").write_text(header + code)

    total = sum(path.stat().st_size for path in gfx_files)
    print(f"Imported {len(gfx_files)} Kim frame files ({total} bytes)")


if __name__ == "__main__":
    main()
